CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" varchar(15) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(15)
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(15) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) NOT NULL,
  "email" varchar(30) UNIQUE NOT NULL,
  "password" varchar(15) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(150),
  "level_id" int NOT NULL,
  "teacher_id" int NOT NULL
);

CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "url" varchar(50) NOT NULL,
  "courses_id" int NOT NULL
);

CREATE TABLE "admin_courses" (
  "admin_id" int NOT NULL,
  "courses_id" int NOT NULL
);

CREATE TABLE "users_courses" (
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "courses_categories" (
  "course_id" int NOT NULL,
  "categorie_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("categorie_id") REFERENCES "categories" ("id");

ALTER TABLE "admin_courses" ADD FOREIGN KEY ("admin_id") REFERENCES "users" ("id");

ALTER TABLE "admin_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "level" ("id");

ALTER TABLE "videos" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");


INSERT INTO roles (rol) VALUES ('alumno'), ('maestro'), ('administrador');

INSERT INTO categories (category) VALUES ('matematicas'), ('programacion');

INSERT INTO level (type) VALUES ('principiantes'), ('intermedio'), ('avanzado');

INSERT INTO users (name, email, password, age, role_id) VALUES ('Alfredo', 'alfred@mail.com', 'alfredocurso', 20, 1), ('Ivan', 'ivan@mail.com', 'ivancurso', 32, 2), ('Josue', 'Josue@mail.com', 'josuecurso', 29, 3);

INSERT INTO courses (title, description, level_id, teacher_id) VALUES ('Matematicas desde cero', 'Curso de matematicas para pricipiantes, aprende lo mas basico', 1, 2), ('Fundamentos de programacion', 'Aprende lo mas basico de programacion, desde logica hasta comandos mas avanzados', 1, 2);

INSERT INTO videos (title, url, courses_id) VALUES ('clase1: introduccion', 'www.cursos.com/clase1-intro', 1), ('clase2: sumas y restas', 'www.cursos.com/clase2-sum', 1), ('clase1: instalacion de programas', 'www.cursos.com/clase1-progra1', 2);

INSERT INTO admin_courses (admin_id, courses_id) VALUES (3, 1), (3, 2);

INSERT INTO users_courses (user_id, course_id) VALUES (1,1), (1,2);

INSERT INTO courses_categories (course_id, categorie_id) VALUES (1,1), (2,2);
